version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: compose/local/app/Dockerfile
    image: webapp
    command: /start
    volumes:
      - .:/fastapi
    ports:
      - 8005:8000
    env_file:
      - .env