"""Init

Revision ID: 10a6d1c85902
Revises: fe42c53efcab
Create Date: 2023-02-05 19:11:21.273911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a6d1c85902'
down_revision = 'fe42c53efcab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
