"""Init

Revision ID: fe42c53efcab
Revises: ae97ee790d20
Create Date: 2023-02-05 19:11:10.213738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe42c53efcab'
down_revision = 'ae97ee790d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
